RevBlog.Web/Controllers/CategoryController.cs
using System.Linq;
using System.Web.Mvc;
using RevBlog.Domain.Abstract;

namespace RevBlog.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository repository;

        public CategoryController(ICategoryRepository repo)
        {
            repository = repo;
        }

        [ChildActionOnly]
        [OutputCache(Duration = 3600)]
        // GET: Category/List
        public PartialViewResult List()
        {
            return PartialView(repository.List.Where(c => c.isActive));
        }
    }
}

RevBlog.Web/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RevBlog.Web.Attributes;

namespace RevBlog.Web.Controllers
{
    [NoCache]
    public class NavController : Controller
    {
        // GET: Nav
        [ChildActionOnly]
        public PartialViewResult Menu()
        {
            return PartialView();
        }
    }
}

RevBlog.Web/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RevBlog.Domain.Abstract;
using RevBlog.Domain.Entities;

namespace RevBlog.Web.Controllers
{
    public class TagController : Controller
    {
        readonly ITagRepository _repository;

        public TagController(ITagRepository repo)
        {
            _repository = repo;
        }

        [ChildActionOnly]
        [OutputCache(Duration = 3600)]
        // GET: Tag/List
        public PartialViewResult List()
        {
            return PartialView(_repository.List.OrderByDescending(t => t.Posts.Count()));
        }
    }
}

RevBlog.Web/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

RevBlog.Web/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

RevBlog.Web/Views/Shared/_Layout.cshtml
@using RevBlog.Web.Extensions.BreadCrumbs;

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - RevBlog</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    @RenderSection("styles", required: false)

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <!--header start-->
    <header class="header-frontend">
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="fa fa-bars"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")">Rev<span>Blog</span></a>
                </div>
                <div class="navbar-collapse collapse ">
                    @Html.Action("Menu", "Nav")
                </div>
            </div>
        </div>
    </header>
    <!--header end-->
    <!--breadcrumbs start-->
    <div class="breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-sm-4">
                    <h1>@ViewBag.Title</h1>
                </div>
                <div class="col-lg-8 col-sm-8">
                    @if(ViewBag.breadCrumb != null)
                    {
                        @((ViewBag.breadCrumb as BreadCrumb).Render());
                    }
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--container start-->
    <div class="container">
        <div class="row">
            <!--blog start-->
            <div class="col-lg-9 ">
                @RenderBody()
            </div>

            <div class="col-lg-3">
                <div class="blog-side-item">
                    <div class="search-row">
                        <form method="get" action="@Url.Action("Search", "Blog")">
                            <input name="q" type="text" class="form-control" placeholder="Поиск" required>
                        </form>
                    </div>
                    
                    @Html.Action("List", "Category")

                    @Html.Action("LastPostsList", "Blog")

                    @Html.Action("List", "Tag")

                    @*
                    <div class="archive">
                        <h3>Archive</h3>
                        <ul class="list-unstyled">
                            <li><a href="javascript:;"><i class="  fa fa-angle-right"></i> May 2013</a></li>
                            <li><a href="javascript:;"><i class="  fa fa-angle-right"></i> April 2013</a></li>
                            <li><a href="javascript:;"><i class="  fa fa-angle-right"></i> March 2013</a></li>
                            <li><a href="javascript:;"><i class="  fa fa-angle-right"></i> February 2013</a></li>
                            <li><a href="javascript:;"><i class="  fa fa-angle-right"></i> January 2013</a></li>
                        </ul>
                    </div>
                    *@

                </div>
            </div>

            <!--blog end-->
        </div>

    </div>
    <!--container end-->
    <!--footer start-->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-3">
                    <h1>Контакты</h1>
                    <address>
                        <p>Email : <a href="mailto:revavg93@gmail.com" rel="nofollow">revavg93@gmail.com</a></p>
                    </address>
                </div>
                <div class="col-lg-3 col-sm-3 col-lg-offset-6">
                    <h1>Я в сети</h1>
                    <ul class="social-link-footer list-unstyled">
                        <li><a href="https://ua.linkedin.com/in/arkadii-hryshko-6380a086" rel="nofollow"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="skype:revavg93" rel="nofollow"><i class="fa fa-skype"></i></a></li>
                        <li><a href="https://github.com/RevProg" rel="nofollow"><i class="fa fa-github"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!--footer end-->


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

    @Scripts.Render("~/Scripts/Custom/common-scripts.js")
</body>
</html>