RevBlog.Web/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RevBlog.Domain.Entities;
using RevBlog.Domain.Abstract;
using RevBlog.Web.Models;

namespace RevBlog.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private IPostRepository postRepository;
        private ICategoryRepository categoryRepository;
        private ITagRepository tagRepository;

        public PostController(IPostRepository postRepo, ICategoryRepository catRepo, ITagRepository tagRepo)
        {
            postRepository = postRepo;
            categoryRepository = catRepo;
            tagRepository = tagRepo;
        }

        // GET: Admin/Post
        public ViewResult Index()
        {
            return View(postRepository.List.Include(p => p.Category).OrderByDescending(p => p.ID).ToList());
        }
        
        // GET: Admin/Post/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Post post = await postRepository.FindWithTagsAsync(id.Value);

            if (post == null)
            {
                return HttpNotFound();
            }

            return View(post);
        }

        // GET: Admin/Post/Create
        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(categoryRepository.List, "ID", "Name");

            return View();
        }

        // POST: Admin/Post/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Title,Alias,CategoryID,Description,Content,MetaDescription,MetaKeyWords,isActive,Created")] Post post)
        {
            post.Created = DateTime.Now;

            if (ModelState.IsValid)
            {
                await postRepository.SaveAsync(post);
                return RedirectToAction("Details", new { id = post.ID });
            }

            ViewBag.CategoryList = new SelectList(categoryRepository.List, "ID", "Name");

            return View(post);
        }

        // GET: Admin/Post/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Post post = await postRepository.FindAsync(id.Value);

            if (post == null)
            {
                return HttpNotFound();
            }

            ViewBag.CategoryList = new SelectList(categoryRepository.List, "ID", "Name");

            return View(post);
        }

        // POST: Admin/Post/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Title,Alias,CategoryID,Description,Content,MetaDescription,MetaKeyWords,isActive,Created")] Post post)
        {
            if (ModelState.IsValid)
            {
                await postRepository.SaveAsync(post);
                return RedirectToAction("Details", new { id = post.ID });
            }

            ViewBag.CategoryList = new SelectList(categoryRepository.List, "ID", "Name");

            return View(post);
        }

        //POST: Admin/Post/AddTag/5
        [HttpPost]
        public async Task<ActionResult> AddTag(int id, string name)
        {
            Post post = await postRepository.FindWithTagsAsync(id);

            if (post == null || name == null)
                return HttpNotFound();

            Tag tag = await tagRepository.FindByNameAsync(name);

            if (tag == null)
            {
                tag = new Tag { Name = name };
                await tagRepository.SaveAsync(tag);
            }
            else
            {
                bool exist = post.Tags.Where(t => t.ID == tag.ID).Count() > 0;

                if (exist)
                    return RedirectToAction("Details", new { id = id });

            }

            post.Tags.Add(tag);

            await postRepository.SaveAsync(post);
                
            return RedirectToAction("Details", new { id = id });
        }

        //POST: Admin/Post/AddTag/5
        [HttpPost]
        public async Task<ActionResult> DeleteTag(int id, int tagID)
        {
            Post post = await postRepository.FindWithTagsAsync(id);
            Tag tag = post.Tags.Where(t => t.ID == tagID).SingleOrDefault();

            if (post == null || tag == null)
                return HttpNotFound();

            post.Tags.Remove(tag);

            await postRepository.SaveAsync(post);
            return RedirectToAction("Details", new { id = id });
        }

        // GET: Admin/Post/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Post post = await postRepository.FindAsync(id.Value);

            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Admin/Post/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await postRepository.DeleteAsync(id);

            return RedirectToAction("Index");
        }
    }
}

RevBlog.Web/Areas/Admin/Views/Post/Create.cshtml
@model RevBlog.Domain.Entities.Post

@{
    ViewBag.Title = "Новая запись";
}

<h2>Добавить запись</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, ViewData.ModelMetadata.DisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryID, ViewBag.CategoryList as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content,  new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MetaDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MetaDescription, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MetaKeyWords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MetaKeyWords, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.MetaKeyWords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isActive)
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Styles {
    @Styles.Render("~/Content/prism.css")
    @Styles.Render("~/Scripts/ckeditor/contents.css")
}

@section Scripts {
    @Scripts.Render("~/Scripts/prism.js")

    @Scripts.Render("~/Scripts/ckeditor/ckeditor.js")
    @Scripts.Render("~/Scripts/ckeditor/config.js")

    <script>
        CKEDITOR.replace('Description');
        CKEDITOR.replace('Content');
    </script>
}

RevBlog.Web/Areas/Admin/Views/Post/Delete.cshtml
@model RevBlog.Domain.Entities.Post

@{
    ViewBag.Title = "Удаление записи";
}

<h2>Удаление</h2>

<h3>Вы уверены что хотите удалить запись?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.Raw(Model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.Raw(Model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaKeyWords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaKeyWords)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

RevBlog.Web/Areas/Admin/Views/Post/Details.cshtml
@model RevBlog.Domain.Entities.Post

@{
    ViewBag.Title = "Просмотр: " + Model.Title;
}

<h2>@ViewBag.Title</h2>

<div>
    <div class="pull-right">
        <a href="@Url.Action("Edit", "Post", new { id = Model.ID })" class="btn btn-warning">Редактировать</a>
        <a href="@Url.Action("Delete", "Post", new { id = Model.ID })" class="btn btn-danger">Удалить</a>
    </div>
    <div class="clearfix"></div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.Raw(Model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.Raw(Model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaKeyWords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaKeyWords)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>
</div>

<div>
    <h2>Теги</h2>

    <table class="table table-striped">
        <tbody>
            @{
                int i = 1;
                foreach (var tag in Model.Tags)
                {
                    <tr>
                        <td>@i</td>
                        <td>@tag.Name</td>
                        <td>
                            @using (Html.BeginForm("DeleteTag", "Post", new { id = Model.ID}, FormMethod.Post))
                            {
                                @Html.Hidden("tagID", tag.ID)
                                <input type="submit" value="Удалить" />
                            }
                        </td>
                    </tr>

                    ++i;
                }
            }
        </tbody>
    </table>

    <h3>Добавить тег</h3>
    @using (Html.BeginForm("AddTag", "Post", new { id = Model.ID }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <div class="form-group">
                @Html.Label("Название", htmlAttributes: new { @class = "control-label col-md-2", required = "required" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.TextBox("Name", null, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Добавить тег" class="btn btn-primary pull-right" />
                </div>
            </div>
        </div>
    }
</div>

<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Назад к списку", "Index")
</p>

@section Styles {
    @Styles.Render("~/Content/prism.css")
}

@section Scripts {
    @Scripts.Render("~/Scripts/prism.js")
}

RevBlog.Web/Areas/Admin/Views/Post/Edit.cshtml
@model RevBlog.Domain.Entities.Post

@{
    ViewBag.Title = "Редактирование записи: " + Model.Title;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, ViewData.ModelMetadata.DisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryID, ViewBag.CategoryList as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MetaDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MetaDescription, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MetaKeyWords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MetaKeyWords, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MetaKeyWords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isActive)
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @Html.HiddenFor(model => model.Created)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Styles {
    @Styles.Render("~/Content/prism.css")
    @Styles.Render("~/Scripts/ckeditor/contents.css")
}

@section Scripts {
    @Scripts.Render("~/Scripts/prism.js")

    @Scripts.Render("~/Scripts/ckeditor/ckeditor.js")
    @Scripts.Render("~/Scripts/ckeditor/config.js")

    <script>
        CKEDITOR.replace('Description');
        CKEDITOR.replace('Content');
    </script>
}

RevBlog.Web/Areas/Admin/Views/Post/Index.cshtml
@model IEnumerable<RevBlog.Domain.Entities.Post>
@using GridMvc.Html
@using GridMvc.Sorting;
@using GridMvc.Filtering;

@{
    ViewBag.Title = "Записи";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Добавить", "Create")
</p>


@Html.Grid(Model).Columns(columns =>
{
    columns.Add(p => p.ID).Sortable(true).SortInitialDirection(GridSortDirection.Descending).Filterable(true);
    columns.Add(p => p.Title).Titled("Заголовок").Sortable(true).Filterable(true).Sanitized(false).Encoded(false).RenderValueAs(model => Html.ActionLink(model.Title,
         "Details", "Post", new { id = model.ID }, null)
         .ToHtmlString());
    columns.Add(p => p.Alias).Titled("Алиас").Sortable(true).Filterable(true);
    columns.Add(p => p.Category.Name).Titled("Категория").Sortable(true);
    columns.Add(p => p.isActive).Titled("Опубликовано?").Sortable(true).Filterable(true);
    columns.Add(p => p.Created).Titled("Дата создания").Sortable(true).Filterable(true).SetFilterWidgetType("System.DateTime");
    columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(model => Html.ActionLink("Редактировать",
        "Edit", "Post", new { id = model.ID }, null)
        .ToHtmlString());
    columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(model => Html.ActionLink("Удалить",
        "Delete", "Post", new { id = model.ID }, null)
        .ToHtmlString());
}).WithPaging(20)


@section Styles {
    @Styles.Render("~/Content/Gridmvc.css")
    @Styles.Render("~/Content/gridmvc.datepicker.min.css")
}

@section Scripts {
    @Scripts.Render("~/Scripts/gridmvc.lang.ru.js")
    @Scripts.Render("~/Scripts/bootstrap-datepicker.js")
    @Scripts.Render("~/Scripts/gridmvc.min.js")
}